# Generated by Django 5.2.9 on 2026-01-27 20:03

from django.db import migrations


def create_rooms(apps, schema_editor):
    Room = apps.get_model("bookings", "Room")

    rooms = [
        {"name": "Spisesal", "color": "#3B82F6", "sort_order": 1},  # Blue
        {"name": "Køkken", "color": "#EF4444", "sort_order": 2},  # Red
        {"name": "Café", "color": "#F59E0B", "sort_order": 3},  # Amber
        {"name": "Væksthuse", "color": "#10B981", "sort_order": 4},  # Emerald
        {"name": "Multirum", "color": "#8B5CF6", "sort_order": 5},  # Violet
        {"name": "Værelse 1", "color": "#EC4899", "sort_order": 6},  # Pink
        {"name": "Værelse 2", "color": "#06B6D4", "sort_order": 7},  # Cyan
        {"name": "Delekontor", "color": "#84CC16", "sort_order": 8},  # Lime
        {"name": "Værksted", "color": "#F97316", "sort_order": 9},  # Orange
    ]

    for room_data in rooms:
        Room.objects.create(
            name=room_data["name"],
            color=room_data["color"],
            sort_order=room_data["sort_order"],
            is_active=True,
        )


def delete_rooms(apps, schema_editor):
    Room = apps.get_model("bookings", "Room")
    Room.objects.filter(
        name__in=[
            "Spisesal",
            "Køkken",
            "Café",
            "Væksthuse",
            "Multirum",
            "Værelse 1",
            "Værelse 2",
            "Delekontor",
            "Værksted",
        ]
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(create_rooms, delete_rooms),
    ]
