# Generated by Django 5.2.9 on 2026-01-28 06:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookings", "0002_seed_rooms"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="recurringbooking",
            options={"ordering": ["room", "start_time"]},
        ),
        migrations.RemoveField(
            model_name="recurringbooking",
            name="day_of_week",
        ),
        migrations.RemoveField(
            model_name="room",
            name="capacity",
        ),
        migrations.AddField(
            model_name="recurringbooking",
            name="days_of_week",
            field=models.JSONField(
                default=list, help_text="List of day integers (0=Monday, 6=Sunday)"
            ),
        ),
        migrations.CreateModel(
            name="RecurringBookingException",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("exception_date", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "recurring_booking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exceptions",
                        to="bookings.recurringbooking",
                    ),
                ),
            ],
            options={
                "ordering": ["exception_date"],
                "unique_together": {("recurring_booking", "exception_date")},
            },
        ),
    ]
