# Generated by Django 5.2.9 on 2025-12-11 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="notificationpreference",
            name="email_digest",
        ),
        migrations.RemoveField(
            model_name="notificationpreference",
            name="email_frequency",
        ),
        migrations.AddField(
            model_name="notificationpreference",
            name="email_announcements",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="notificationpreference",
            name="email_event_reminders",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="notificationpreference",
            name="email_food_tickets",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="notificationpreference",
            name="email_forum_subscriptions",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="notificationpreference",
            name="email_messages",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="notificationpreference",
            name="email_thread_replies",
            field=models.BooleanField(default=False),
        ),
    ]
