# Generated by Django 5.2.9 on 2026-01-11 20:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0003_add_push_subscriptions"),
    ]

    operations = [
        migrations.AddField(
            model_name="notificationpreference",
            name="email_post_reactions",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="notificationpreference",
            name="notify_post_reactions",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="notificationpreference",
            name="push_post_reactions",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("new_message", "New Message"),
                    ("new_announcement", "New Announcement"),
                    ("new_thread", "New Thread in Subscribed Subgroup"),
                    ("thread_reply", "Reply to Your Thread"),
                    ("post_reply", "Reply to Your Post"),
                    ("post_reaction", "Reaction to Your Post"),
                    ("event_reminder", "Event Reminder"),
                    ("food_ticket", "Food Ticket Available"),
                ],
                max_length=50,
            ),
        ),
    ]
