# Generated by Django 5.2.9 on 2026-02-17 19:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0005_alter_notification_notification_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="notificationpreference",
            name="email_events",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="notificationpreference",
            name="notify_events",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="notificationpreference",
            name="push_events",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("new_message", "Ny besked"),
                    ("new_announcement", "Ny vigtig post"),
                    ("new_thread", "Ny tråd i gruppen"),
                    ("thread_reply", "Nyt svar i tråden"),
                    ("post_reply", "Nyt svar på dit opslag"),
                    ("post_reaction", "Reaktion på dit opslag"),
                    ("event_created", "Nyt arrangement"),
                    ("event_updated", "Arrangement opdateret"),
                    ("event_reminder", "Begivenhedsreminder"),
                    ("food_ticket", "Madbillet tilgængelig"),
                ],
                max_length=50,
            ),
        ),
    ]
