# Generated by Django 5.2.9 on 2026-02-18 19:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0006_notificationpreference_email_events_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("new_message", "Ny besked"),
                    ("new_announcement", "Ny vigtig post"),
                    ("new_thread", "Ny tråd i gruppen"),
                    ("thread_reply", "Nyt svar i tråden"),
                    ("post_reply", "Nyt svar på dit opslag"),
                    ("post_reaction", "Reaktion på dit opslag"),
                    ("event_created", "Nyt arrangement"),
                    ("event_updated", "Arrangement opdateret"),
                    ("event_cancelled", "Arrangement aflyst"),
                    ("event_reminder", "Begivenhedsreminder"),
                    ("food_ticket", "Madbillet tilgængelig"),
                ],
                max_length=50,
            ),
        ),
    ]
