# Generated by Django 5.2.9 on 2026-02-27 15:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0008_notificationpreference_email_mentions_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="notificationpreference",
            name="email_announcement_updates",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="notificationpreference",
            name="email_subgroup_activity",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="notificationpreference",
            name="notify_announcement_updates",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="notificationpreference",
            name="notify_subgroup_activity",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="notificationpreference",
            name="push_announcement_updates",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="notificationpreference",
            name="push_subgroup_activity",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("new_message", "Ny besked"),
                    ("new_announcement", "Ny vigtig post"),
                    ("announcement_updated", "Vigtig post opdateret"),
                    ("new_thread", "Ny tråd i gruppen"),
                    ("thread_reply", "Nyt svar i tråden"),
                    ("post_reply", "Nyt svar på dit opslag"),
                    ("subgroup_activity", "Ny aktivitet i gruppen"),
                    ("post_reaction", "Reaktion på dit opslag"),
                    ("event_created", "Nyt arrangement"),
                    ("event_updated", "Arrangement opdateret"),
                    ("event_cancelled", "Arrangement aflyst"),
                    ("event_reminder", "Begivenhedsreminder"),
                    ("food_ticket", "Madbillet tilgængelig"),
                    ("mention", "Omtale"),
                ],
                max_length=50,
            ),
        ),
    ]
