# Generated by Django 5.2.9 on 2026-03-02 13:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0009_announcement_updated_subgroup_activity"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="notification",
            options={"ordering": ["-updated_at"]},
        ),
        migrations.AddField(
            model_name="notification",
            name="aggregate_count",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="notification",
            name="group_key",
            field=models.CharField(blank=True, db_index=True, max_length=500),
        ),
        migrations.AddField(
            model_name="notification",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
