# Generated by Django 5.2.9 on 2026-05-26 10:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0014_notification_notif_user_recent_idx_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="notificationpreference",
            old_name="notify_messages",
            new_name="notify_message_reactions",
        ),
    ]
