# Generated by Django 5.2.9 on 2026-05-27 21:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "notifications",
            "0015_rename_notify_messages_notificationpreference_notify_message_reactions",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="notificationpreference",
            name="email_food_leftovers_ready",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="notificationpreference",
            name="email_food_swap_request",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="notificationpreference",
            name="email_food_takeaway_ready",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="notificationpreference",
            name="email_food_team_reminder",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="notificationpreference",
            name="notify_food_leftovers_ready",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="notificationpreference",
            name="notify_food_swap_request",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="notificationpreference",
            name="notify_food_takeaway_ready",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="notificationpreference",
            name="notify_food_team_reminder",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="notificationpreference",
            name="push_food_leftovers_ready",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="notificationpreference",
            name="push_food_swap_request",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="notificationpreference",
            name="push_food_takeaway_ready",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="notificationpreference",
            name="push_food_team_reminder",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("new_message", "Ny besked"),
                    ("message_reaction", "Reaktion på din besked"),
                    ("new_announcement", "Ny vigtig post"),
                    ("announcement_updated", "Vigtig post opdateret"),
                    ("new_thread", "Ny tråd i gruppen"),
                    ("thread_reply", "Nyt svar i tråden"),
                    ("post_reply", "Nyt svar på dit opslag"),
                    ("subgroup_activity", "Ny aktivitet i gruppen"),
                    ("post_reaction", "Reaktion på dit opslag"),
                    ("event_created", "Nyt arrangement"),
                    ("event_updated", "Arrangement opdateret"),
                    ("event_cancelled", "Arrangement aflyst"),
                    ("event_reminder", "Begivenhedsreminder"),
                    ("food_ticket", "Madbillet tilgængelig"),
                    ("food_team_reminder", "Madlavning i morgen"),
                    ("food_takeaway_ready", "Takeaway er klar"),
                    ("food_leftovers_ready", "Rester er klar"),
                    ("food_swap_request", "Bytteanmodning til madhold"),
                    ("mention", "Omtale"),
                    ("subgroup_member_added", "Tilføjet som medlem"),
                    ("subgroup_member_removed", "Fjernet som medlem"),
                    (
                        "post_edited_by_admin",
                        "Dit indhold blev redigeret af en administrator",
                    ),
                    (
                        "event_edited_by_admin",
                        "Din begivenhed blev redigeret af en administrator",
                    ),
                    (
                        "announcement_edited_by_admin",
                        "Dit opslag blev redigeret af en administrator",
                    ),
                ],
                max_length=50,
            ),
        ),
    ]
