# Generated by Django 5.2.9 on 2026-06-13 09:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "notifications",
            "0015_rename_notify_messages_notificationpreference_notify_message_reactions",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("new_message", "Ny besked"),
                    ("message_reaction", "Reaktion på din besked"),
                    ("new_announcement", "Ny vigtig post"),
                    ("announcement_updated", "Vigtig post opdateret"),
                    ("new_thread", "Ny tråd i gruppen"),
                    ("thread_reply", "Nyt svar i tråden"),
                    ("post_reply", "Nyt svar på dit opslag"),
                    ("subgroup_activity", "Ny aktivitet i gruppen"),
                    ("post_reaction", "Reaktion på dit opslag"),
                    ("event_created", "Nyt arrangement"),
                    ("event_updated", "Arrangement opdateret"),
                    ("event_cancelled", "Arrangement aflyst"),
                    ("event_reminder", "Begivenhedsreminder"),
                    ("food_ticket", "Madbillet tilgængelig"),
                    ("mention", "Omtale"),
                    ("subgroup_member_added", "Tilføjet som medlem"),
                    ("subgroup_member_removed", "Fjernet som medlem"),
                    (
                        "post_edited_by_admin",
                        "Dit indhold blev redigeret af en administrator",
                    ),
                    (
                        "event_edited_by_admin",
                        "Din begivenhed blev redigeret af en administrator",
                    ),
                    (
                        "announcement_edited_by_admin",
                        "Dit opslag blev redigeret af en administrator",
                    ),
                    ("expense_processed", "Udlæg behandlet"),
                ],
                max_length=50,
            ),
        ),
    ]
