# Generated by Django 5.2.9 on 2026-05-27 21:26

from django.db import migrations

# Mon-Thu (cooking days). MealPreference.day_of_week uses 0=Mon..3=Thu.
_WEEKDAYS = {0, 1, 2, 3}


def derive_food_notification_defaults(apps, schema_editor):
    """Seed the new food-team preferences from each user's house meal preferences.

    - takeaway_ready: enabled IFF the house has ANY take_away meal preference.
    - leftovers_ready: enabled IFF the house has 17:30-seating preferences for >=3 weekdays.

    Users with no house or no meal preferences keep the model defaults (all True).
    food_team_reminder and food_swap_request always keep their model default (True).
    """
    NotificationPreference = apps.get_model("notifications", "NotificationPreference")
    MealPreference = apps.get_model("food", "MealPreference")

    for prefs in NotificationPreference.objects.select_related("user").iterator():
        house_id = prefs.user.house_id
        if not house_id:
            continue

        house_prefs = list(
            MealPreference.objects.filter(house_id=house_id).values(
                "day_of_week", "dining_option", "seating_time"
            )
        )
        if not house_prefs:
            continue

        has_takeaway = any(mp["dining_option"] == "take_away" for mp in house_prefs)
        first_seating_weekdays = {
            mp["day_of_week"]
            for mp in house_prefs
            if mp["seating_time"] == "17:30" and mp["day_of_week"] in _WEEKDAYS
        }
        has_leftovers = len(first_seating_weekdays) >= 3

        prefs.notify_food_takeaway_ready = has_takeaway
        prefs.push_food_takeaway_ready = has_takeaway
        prefs.notify_food_leftovers_ready = has_leftovers
        prefs.push_food_leftovers_ready = has_leftovers
        prefs.save(
            update_fields=[
                "notify_food_takeaway_ready",
                "push_food_takeaway_ready",
                "notify_food_leftovers_ready",
                "push_food_leftovers_ready",
            ]
        )


def reverse_noop(apps, schema_editor):
    """No-op: derived defaults are not reversible."""


class Migration(migrations.Migration):
    dependencies = [
        (
            "notifications",
            "0016_notificationpreference_email_food_leftovers_ready_and_more",
        ),
        ("food", "0022_drivemenucache_recipe_file_id_and_more"),
    ]

    operations = [
        migrations.RunPython(derive_food_notification_defaults, reverse_noop),
    ]
