# Generated by Django 5.2.9 on 2026-08-10 13:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0017_alter_notification_notification_type"),
        ("notifications", "0017_derive_food_notification_defaults"),
    ]

    operations = []
