# Generated by Django 5.2.9 on 2026-08-21 19:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0019_alter_notification_notification_type"),
        ("notifications", "0019_alter_notificationpreference_email_car_sharing"),
    ]

    operations = []
