# Generated by Django 5.2.9 on 2026-08-21 19:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0020_merge_20260821_2114"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("new_message", "Ny besked"),
                    ("message_reaction", "Reaktion på din besked"),
                    ("new_announcement", "Ny vigtig post"),
                    ("announcement_updated", "Vigtig post opdateret"),
                    ("new_thread", "Ny tråd i gruppen"),
                    ("thread_reply", "Nyt svar i tråden"),
                    ("post_reply", "Nyt svar på dit opslag"),
                    ("subgroup_activity", "Ny aktivitet i gruppen"),
                    ("post_reaction", "Reaktion på dit opslag"),
                    ("event_created", "Ny begivenhed"),
                    ("event_updated", "Begivenhed opdateret"),
                    ("event_cancelled", "Begivenhed aflyst"),
                    ("event_reminder", "Begivenhedsreminder"),
                    ("food_ticket", "Madbillet tilgængelig"),
                    ("food_team_reminder", "Madlavning i morgen"),
                    ("food_takeaway_ready", "Takeaway er klar"),
                    ("food_leftovers_ready", "Rester er klar"),
                    ("food_swap_request", "Bytteanmodning til madhold"),
                    ("mention", "Omtale"),
                    ("subgroup_member_added", "Tilføjet som medlem"),
                    ("subgroup_member_removed", "Fjernet som medlem"),
                    (
                        "post_edited_by_admin",
                        "Dit indhold blev redigeret af en administrator",
                    ),
                    (
                        "event_edited_by_admin",
                        "Din begivenhed blev redigeret af en administrator",
                    ),
                    (
                        "announcement_edited_by_admin",
                        "Dit opslag blev redigeret af en administrator",
                    ),
                    ("expense_processed", "Udlæg behandlet"),
                    ("car_loan_request", "Forespørgsel om at låne din bil"),
                    ("car_loan_update", "Opdatering om bildeling"),
                ],
                max_length=50,
            ),
        ),
    ]
