# Generated by Django 5.2.9 on 2025-12-12 17:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_add_house_to_invitation"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="can_be_head_chef",
            field=models.BooleanField(
                default=False,
                help_text="User can be head chef (at least 1 required per team)",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="food_team_comment",
            field=models.TextField(
                blank=True, help_text="Special notes about food team participation"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="is_exempt_from_food_teams",
            field=models.BooleanField(
                default=False,
                help_text="User is exempt from food team duty (e.g., buyers, special circumstances)",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="is_over_50",
            field=models.BooleanField(
                default=False, help_text="User is over 50 (max 2 per team for balance)"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="prefers_cooking_with_housemate",
            field=models.BooleanField(
                default=False,
                help_text="User prefers to be on the same team as their housemate",
            ),
        ),
    ]
