# Generated by Django 5.2.9 on 2025-12-13 20:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_add_food_team_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="default_cooking_days",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Default days of the week user is available to cook (0=Mon, 1=Tue, 2=Wed, 3=Thu)",
            ),
        ),
    ]
