# Generated by Django 5.2.9 on 2026-02-26 20:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0006_email_change_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="accessibility_mode",
            field=models.BooleanField(
                default=False,
                help_text="User prefers larger text and higher contrast (for visually impaired)",
            ),
        ),
    ]
