# Generated by Django 5.2.9 on 2026-04-09 08:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0007_add_accessibility_mode"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_food_admin",
            field=models.BooleanField(
                default=False,
                help_text="User has food admin privileges (cost reports, refresh menus, etc.)",
            ),
        ),
    ]
