# Generated by Django 5.2.9 on 2026-04-24 20:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0008_user_is_food_admin"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="bio",
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
