# Generated by Django 5.2.9 on 2026-04-30 19:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0009_alter_user_bio"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="hide_closed_threads",
            field=models.BooleanField(
                default=False, help_text="Hide closed threads from subgroup thread lists"
            ),
        ),
    ]
