# Generated by Django 5.2.9 on 2026-05-20 08:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0010_user_hide_closed_threads"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="profile_picture_thumbnail",
            field=models.ImageField(
                blank=True,
                help_text="400x400 JPEG square crop, generated server-side on upload.",
                null=True,
                upload_to="profile_pictures/thumbs/",
            ),
        ),
    ]
