# Generated by Django 5.2.9 on 2026-06-13 09:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0011_user_profile_picture_thumbnail"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_economy_admin",
            field=models.BooleanField(
                default=False,
                help_text="User has economy admin privileges (manage udlæg/expense reimbursements and view the food cost report).",
            ),
        ),
    ]
