# Generated by Django 5.2.9 on 2026-06-13 20:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0012_user_is_economy_admin"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="bank_account_number",
            field=models.CharField(
                blank=True,
                help_text="Kontonummer til udbetaling af udlæg",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="bank_reg_nr",
            field=models.CharField(
                blank=True,
                help_text="Bank reg. nr. (4 cifre) til udbetaling af udlæg",
                max_length=10,
            ),
        ),
    ]
