# Generated by Django 5.2.9 on 2026-08-06 11:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0013_user_bank_account_number_user_bank_reg_nr"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="carsharing_terms_accepted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="carsharing_terms_accepted_version",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Version of the car sharing loan terms accepted as a borrower",
                max_length=20,
            ),
        ),
    ]
