# Generated by Django 5.2.9 on 2026-08-10 13:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0012_seed_food_team_flags"),
        ("users", "0013_user_bank_account_number_user_bank_reg_nr"),
    ]

    operations = []
