# Generated by Django 5.2.9 on 2026-08-21 19:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0014_merge_20260810_1522"),
        ("users", "0014_user_carsharing_terms_accepted_at_and_more"),
    ]

    operations = []
