# Generated by Django 5.2.9 on 2026-08-21 20:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0015_lowercase_user_emails"),
        ("users", "0015_merge_20260821_2114"),
    ]

    operations = []
