# Generated by Django 5.2.9 on 2026-09-24 09:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0015_lowercase_user_emails"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_food_economy_admin",
            field=models.BooleanField(
                default=False,
                help_text="Madøkonomiansvarlig: gets the notice for udlæg to fællesmad and may mark those (only those) paid or rejected.",
            ),
        ),
    ]
