# Generated by Django 5.2.9 on 2026-08-22 05:49

"""Drop the free-text profile comment; add a reason tied to the pause switch.

food_team_comment was addressed "til madhold-ansvarlig" but was exposed only on
my-food-profile, so its only reader was its author. It was empty for all 111
users, so this drops rather than migrates it. The replacement is bound to
is_exempt_from_food_teams and is shown to food admins.
"""

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0016_merge_20260821_2248"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="food_team_comment",
        ),
        migrations.AddField(
            model_name="user",
            name="food_team_pause_reason",
            field=models.TextField(
                blank=True,
                help_text="Why this user is stepping back from food teams, shown to food admins next to is_exempt_from_food_teams. Free text: 'away until spring', 'health', or nothing at all.",
            ),
        ),
    ]
