# Generated by Django 5.2.9 on 2026-09-05 19:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0017_remove_user_food_team_comment_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="is_over_50",
            field=models.BooleanField(
                default=False,
                help_text="Fallback for residents without a birthdate — read via is_over_50_effective, never directly (max 2 per team for balance)",
            ),
        ),
    ]
