# Generated by Django 5.2.9 on 2026-09-25 06:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0016_user_is_food_economy_admin"),
        ("users", "0018_alter_user_is_over_50"),
    ]

    operations = []
