# Generated by Django 5.2.9 on 2026-09-25 08:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0019_merge_20260925_0848"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="hide_birth_year",
            field=models.BooleanField(
                default=False,
                help_text="Show others only the day and month of the birthday, never the year or age",
            ),
        ),
    ]
