# Generated by Django 5.2.9 on 2026-01-22 18:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("messaging", "0002_messageattachment"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="is_system_message",
            field=models.BooleanField(default=False),
        ),
    ]
