# Generated by Django 5.2.9 on 2026-02-19 08:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("messaging", "0003_message_is_system_message"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="edited_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="message",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
