# Generated by Django 5.2.9 on 2026-03-04 12:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("messaging", "0005_add_message_reaction"),
    ]

    operations = [
        migrations.AddField(
            model_name="messageattachment",
            name="preview_html",
            field=models.TextField(blank=True, default=""),
        ),
    ]
