# Generated by Django 5.2.9 on 2026-03-07 19:24

from django.db import migrations

import apps.messaging.encryption


class Migration(migrations.Migration):
    dependencies = [
        ("messaging", "0007_encrypted_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="content",
            field=apps.messaging.encryption.EncryptedTextField(),
        ),
    ]
