# Generated by Django 5.2.9 on 2026-03-23 19:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("messaging", "0009_alter_messagereaction_reaction_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="name",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
    ]
