# Generated by Django 5.2.9 on 2026-05-03 12:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("messaging", "0013_migrate_reaction_slugs_to_emoji"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="message",
            index=models.Index(fields=["conversation", "sender"], name="msg_conv_sender_idx"),
        ),
        migrations.AddIndex(
            model_name="messagereadstatus",
            index=models.Index(fields=["user", "message"], name="msg_read_user_msg_idx"),
        ),
    ]
