# Generated by Django 5.2.9 on 2026-06-30 20:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("messaging", "0014_message_msg_conv_sender_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="messageattachment",
            name="preview",
            field=models.ImageField(
                blank=True,
                help_text="Full-size web-viewable JPEG for formats browsers can't render (e.g. HEIC).",
                null=True,
                upload_to="message_attachments/previews/",
            ),
        ),
    ]
