# Generated by Django 5.2.9 on 2026-09-25 09:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("messaging", "0015_messageattachment_preview"),
    ]

    operations = [
        migrations.AddField(
            model_name="messageattachment",
            name="thumbnail",
            field=models.ImageField(
                blank=True,
                help_text="400px square JPEG for the chat bubble.",
                null=True,
                upload_to="message_attachments/thumbs/",
            ),
        ),
    ]
