# Generated by Django 5.2.9 on 2026-06-13 20:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("expenses", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="expense",
            name="food_related",
            field=models.BooleanField(
                default=False,
                help_text="Udlæg i forbindelse med fællesmad — gør det synligt for madansvarlige.",
            ),
        ),
    ]
