# Generated by Django 5.2.9 on 2026-02-18 18:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0003_event_rooms_m2m"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="cancellation_message",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="event",
            name="is_cancelled",
            field=models.BooleanField(default=False),
        ),
    ]
