# Generated by Django 5.2.9 on 2026-03-02 13:23

from django.db import migrations, models
from django.utils.text import slugify


def generate_event_slugs(apps, schema_editor):
    Event = apps.get_model("events", "Event")
    for event in Event.objects.all().order_by("id"):
        base = slugify(event.title, allow_unicode=True) or "arrangement"
        slug = base
        n = 2
        while Event.objects.filter(slug=slug).exclude(pk=event.pk).exists():
            slug = f"{base}-{n}"
            n += 1
        event.slug = slug
        event.save(update_fields=["slug"])


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0005_event_thread"),
    ]

    operations = [
        # Add without unique first so backfill can run
        migrations.AddField(
            model_name="event",
            name="slug",
            field=models.SlugField(allow_unicode=True, blank=True, max_length=255),
        ),
        migrations.RunPython(generate_event_slugs, migrations.RunPython.noop),
        # Now add the unique constraint
        migrations.AlterField(
            model_name="event",
            name="slug",
            field=models.SlugField(allow_unicode=True, blank=True, max_length=255, unique=True),
        ),
    ]
