# Generated by Django 5.2.9 on 2026-07-31 22:56

from decimal import Decimal

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("houses", "0010_car_color_car_dogs_allowed_car_equipment_note_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CarBlock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "days_of_week",
                    models.JSONField(
                        default=list, help_text="List of day integers (0=Monday, 6=Sunday)"
                    ),
                ),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("note", models.CharField(blank=True, default="", max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "car",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blocks",
                        to="houses.car",
                    ),
                ),
            ],
            options={
                "ordering": ["start_time"],
            },
        ),
        migrations.CreateModel(
            name="CarLoan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("requested", "Forespurgt"),
                            ("active", "Aktivt"),
                            ("completed", "Afsluttet"),
                            ("cancelled", "Aflyst"),
                        ],
                        db_index=True,
                        default="requested",
                        max_length=20,
                    ),
                ),
                ("start_at", models.DateTimeField()),
                ("end_at", models.DateTimeField()),
                ("expected_km", models.PositiveIntegerField()),
                ("needs_isofix", models.BooleanField(default=False)),
                ("needs_tow_hitch", models.BooleanField(default=False)),
                ("min_seats", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("note", models.TextField(blank=True, default="")),
                ("terms_version", models.CharField(max_length=20)),
                (
                    "rate_per_km",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
                ),
                ("activated_at", models.DateTimeField(blank=True, null=True)),
                ("actual_km", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "expense_amount",
                    models.DecimalField(decimal_places=2, default=Decimal("0"), max_digits=7),
                ),
                ("expense_note", models.CharField(blank=True, default="", max_length=200)),
                ("damage_note", models.TextField(blank=True, default="")),
                (
                    "amount_due",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
                ),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_car_loans",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "borrower",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="car_loans",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "car",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="loans",
                        to="houses.car",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CarLoanCandidate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("asked", "Spurgt"),
                            ("accepted", "Accepteret"),
                            ("declined", "Afvist"),
                            ("closed", "Låneren valgte en anden"),
                        ],
                        db_index=True,
                        default="asked",
                        max_length=20,
                    ),
                ),
                ("responded_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "car",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="loan_candidacies",
                        to="houses.car",
                    ),
                ),
                (
                    "loan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="candidates",
                        to="carsharing.carloan",
                    ),
                ),
                (
                    "responded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="car_loan_responses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("loan", "car"), name="unique_loan_car_candidate"
                    )
                ],
            },
        ),
    ]
