# Generated by Django 5.2.9 on 2026-08-01 00:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("carsharing", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="carblock",
            name="note",
        ),
    ]
