# Generated by Django 5.2.9 on 2025-12-11 21:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("food", "0001_initial"),
        ("houses", "0002_add_house_profile_picture"),
    ]

    operations = [
        migrations.AddField(
            model_name="mealpreference",
            name="dining_option",
            field=models.CharField(
                choices=[("eat_in", "Eat In"), ("take_away", "Take Away")],
                default="eat_in",
                help_text="Default dining preference (eat in or take away)",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="mealpreference",
            name="seating_time",
            field=models.CharField(
                choices=[("17:30", "17:30"), ("18:30", "18:30")],
                default="17:30",
                help_text="Default seating time preference",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="mealregistration",
            name="dining_option",
            field=models.CharField(
                choices=[("eat_in", "Eat In"), ("take_away", "Take Away")],
                default="eat_in",
                help_text="Eat in or take away",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="mealregistration",
            name="house",
            field=models.ForeignKey(
                blank=True,
                help_text="If set, this is a registration on behalf of the house",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="meal_registrations",
                to="houses.house",
            ),
        ),
        migrations.AddField(
            model_name="mealregistration",
            name="seating_time",
            field=models.CharField(
                choices=[("17:30", "17:30"), ("18:30", "18:30")],
                default="17:30",
                help_text="17:30 or 18:30 seating",
                max_length=10,
            ),
        ),
    ]
