# Generated by Django 5.2.9 on 2025-12-12 06:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("food", "0002_add_dining_seating_house"),
    ]

    operations = [
        migrations.CreateModel(
            name="MenuTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Short name/header for the menu (e.g., 'Lasagne', 'Thai Curry')",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Full description of the menu"),
                ),
                (
                    "has_meat_option",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this menu has separate meat/vegetarian options",
                    ),
                ),
                (
                    "meat_description",
                    models.TextField(
                        blank=True,
                        help_text="Description of meat option (if applicable)",
                    ),
                ),
                (
                    "vegetarian_description",
                    models.TextField(
                        blank=True,
                        help_text="Description of vegetarian option (if applicable)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AlterField(
            model_name="dailymenu",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Main menu description (overrides template if set)",
            ),
        ),
        migrations.AddField(
            model_name="dailymenu",
            name="template",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional link to a reusable menu template",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="daily_menus",
                to="food.menutemplate",
            ),
        ),
    ]
