# Generated by Django 5.2.9 on 2025-12-12 06:50

from django.db import migrations


def create_menu_templates(apps, schema_editor):
    """Create sample menu templates."""
    MenuTemplate = apps.get_model("food", "MenuTemplate")

    templates = [
        {
            "name": "Lasagne",
            "description": "Klassisk italiensk lasagne med bechamelsauce og frisk salat",
            "has_meat_option": True,
            "meat_description": "Lasagne med oksekød, tomatsauce og ost",
            "vegetarian_description": "Grøntsagslasagne med spinat, squash og ricotta",
        },
        {
            "name": "Thai Karry",
            "description": "Autentisk thai karry med jasminris og friske grøntsager",
            "has_meat_option": True,
            "meat_description": "Kylling i grøn karry med kokosmælk",
            "vegetarian_description": "Grøntsagskarry med tofu og kokosmælk",
        },
        {
            "name": "Frikadeller",
            "description": "Hjemmelavede frikadeller med kartofler og brun sovs",
            "has_meat_option": True,
            "meat_description": "Klassiske svinekødsfrikadeller",
            "vegetarian_description": "Grøntsagsfrikadeller med kikærter og gulerødder",
        },
        {
            "name": "Pasta Bolognese",
            "description": "Spaghetti bolognese med parmesan og hvidløgsbrød",
            "has_meat_option": True,
            "meat_description": "Traditionel bolognese med oksekød",
            "vegetarian_description": "Linse-bolognese med grøntsager",
        },
        {
            "name": "Indisk Dal",
            "description": "Krydret linsesuppe med naanbrød og raita",
            "has_meat_option": False,
            "meat_description": "",
            "vegetarian_description": "",
        },
        {
            "name": "Stegt Flæsk",
            "description": "Stegt flæsk med persillesovs og kogte kartofler",
            "has_meat_option": True,
            "meat_description": "Sprødt stegt flæsk med persillesovs",
            "vegetarian_description": "Stegte grøntsager med persillesovs",
        },
    ]

    for template_data in templates:
        MenuTemplate.objects.create(**template_data)


def delete_menu_templates(apps, schema_editor):
    """Remove the sample menu templates."""
    MenuTemplate = apps.get_model("food", "MenuTemplate")
    MenuTemplate.objects.filter(
        name__in=[
            "Lasagne",
            "Thai Karry",
            "Frikadeller",
            "Pasta Bolognese",
            "Indisk Dal",
            "Stegt Flæsk",
        ]
    ).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("food", "0003_add_menu_template"),
    ]

    operations = [
        migrations.RunPython(create_menu_templates, delete_menu_templates),
    ]
