# Generated by Django 5.2.9 on 2025-12-12

from datetime import timedelta

from django.db import migrations
from django.utils import timezone


def get_week_start(d):
    """Get the Monday of the week containing the given date."""
    return d - timedelta(days=d.weekday())


def create_weekly_menus(apps, schema_editor):
    """Create sample weekly menus for current and upcoming weeks."""
    WeeklyMenu = apps.get_model("food", "WeeklyMenu")
    DailyMenu = apps.get_model("food", "DailyMenu")
    MenuTemplate = apps.get_model("food", "MenuTemplate")

    # Get all templates
    templates = list(MenuTemplate.objects.all())
    if not templates:
        return  # No templates to assign

    # Get today and calculate week starts
    today = timezone.now().date()
    current_week_start = get_week_start(today)

    # Create menus for current week and next 3 weeks
    template_index = 0
    for week_offset in range(4):
        week_start = current_week_start + timedelta(weeks=week_offset)

        # Check if menu already exists
        if WeeklyMenu.objects.filter(week_start_date=week_start).exists():
            continue

        # Create weekly menu
        weekly_menu = WeeklyMenu.objects.create(
            week_start_date=week_start,
            created_by=None,  # System-created
        )

        # Create daily menus for Mon-Thu and assign templates
        for day in range(4):  # 0=Mon, 1=Tue, 2=Wed, 3=Thu
            menu_date = week_start + timedelta(days=day)
            template = templates[template_index % len(templates)]

            DailyMenu.objects.create(
                weekly_menu=weekly_menu,
                date=menu_date,
                day_of_week=day,
                template=template,
                has_meat_option=(day == 2),  # Wednesday has meat option
            )

            template_index += 1


def delete_weekly_menus(apps, schema_editor):
    """Remove the created weekly menus."""
    WeeklyMenu = apps.get_model("food", "WeeklyMenu")
    # Only delete menus created by the system (no created_by)
    WeeklyMenu.objects.filter(created_by__isnull=True).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("food", "0004_seed_menu_templates"),
    ]

    operations = [
        migrations.RunPython(create_weekly_menus, delete_weekly_menus),
    ]
