# Generated by Django 5.2.9 on 2025-12-12 12:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("food", "0005_seed_weekly_menus"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FoodTeam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateField(help_text="The date this team is cooking", unique=True),
                ),
                (
                    "notes",
                    models.TextField(blank=True, help_text="Optional notes about this team/day"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["date"],
            },
        ),
        migrations.CreateModel(
            name="FoodTeamMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "house_number",
                    models.CharField(
                        blank=True,
                        help_text="House number at time of assignment (for display)",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="food.foodteam",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="food_team_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["team__date", "user__first_name"],
                "unique_together": {("team", "user")},
            },
        ),
        migrations.CreateModel(
            name="TeamSwapRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("declined", "Declined"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "message",
                    models.TextField(blank=True, help_text="Optional message from requester"),
                ),
                (
                    "response_message",
                    models.TextField(blank=True, help_text="Optional response message"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "requester",
                    models.ForeignKey(
                        help_text="User requesting the swap",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_swap_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "requester_membership",
                    models.ForeignKey(
                        help_text="The requester's team membership to swap",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outgoing_swap_requests",
                        to="food.foodteammember",
                    ),
                ),
                (
                    "target_membership",
                    models.ForeignKey(
                        help_text="The target's team membership to swap with",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incoming_swap_requests",
                        to="food.foodteammember",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
