# Generated by Django 5.2.9 on 2025-12-12 12:32

from datetime import timedelta

from django.db import migrations


def seed_food_teams(apps, schema_editor):
    """Seed food teams for the next 4 weeks (16 cooking days)."""
    from datetime import date

    FoodTeam = apps.get_model("food", "FoodTeam")
    FoodTeamMember = apps.get_model("food", "FoodTeamMember")
    User = apps.get_model("users", "User")

    # Get all users (we'll cycle through them)
    users = list(User.objects.all().order_by("id"))
    if len(users) < 1:
        print("No users found, skipping team seeding.")
        return

    # Determine team size (6 if we have enough users, otherwise use what we have)
    team_size = min(6, len(users))

    # Calculate next Monday
    today = date.today()
    days_until_monday = (7 - today.weekday()) % 7
    if days_until_monday == 0:
        days_until_monday = 7  # If today is Monday, start next Monday
    next_monday = today + timedelta(days=days_until_monday)

    # Create teams for 4 weeks (Mon-Thu each week)
    user_index = 0
    team_count = 0

    for week in range(4):
        week_start = next_monday + timedelta(weeks=week)

        for day_offset in range(4):  # Mon, Tue, Wed, Thu
            team_date = week_start + timedelta(days=day_offset)

            # Create the team
            team = FoodTeam.objects.create(
                date=team_date,
                notes="",
            )

            # Add members to the team (up to 6, or however many users we have)
            for _ in range(team_size):
                user = users[user_index % len(users)]
                house_number = ""
                if hasattr(user, "house") and user.house or hasattr(user, "house_id") and user.house_id:
                    house_number = str(user.house_id)

                FoodTeamMember.objects.create(
                    team=team,
                    user=user,
                    house_number=house_number,
                )
                user_index += 1

            team_count += 1

    print(f"Created {team_count} food teams with {team_size} members each.")


def reverse_seed_food_teams(apps, schema_editor):
    """Remove seeded food teams."""
    FoodTeam = apps.get_model("food", "FoodTeam")
    FoodTeam.objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ("food", "0006_food_teams"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(seed_food_teams, reverse_seed_food_teams),
    ]
