# Generated by Django 5.2.9 on 2025-12-12 17:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("food", "0007_seed_food_teams"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FoodTeamCycle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Descriptive name for the cycle (e.g., 'December 2025 - January 2026')",
                        max_length=100,
                    ),
                ),
                (
                    "start_date",
                    models.DateField(help_text="First cooking day of the cycle (must be a Monday)"),
                ),
                (
                    "end_date",
                    models.DateField(
                        help_text="Last cooking day of the cycle (must be a Thursday)"
                    ),
                ),
                (
                    "wish_deadline",
                    models.DateTimeField(help_text="Deadline for submitting date wishes"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("collecting_wishes", "Collecting Wishes"),
                            ("generating", "Generating Teams"),
                            ("finalized", "Finalized"),
                            ("archived", "Archived"),
                        ],
                        default="collecting_wishes",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_cycles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-start_date"],
            },
        ),
        migrations.AddField(
            model_name="foodteam",
            name="cycle",
            field=models.ForeignKey(
                blank=True,
                help_text="The cycle this team belongs to",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="teams",
                to="food.foodteamcycle",
            ),
        ),
        migrations.CreateModel(
            name="FoodTeamWish",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "available_dates",
                    models.JSONField(
                        default=list,
                        help_text="List of date strings (YYYY-MM-DD) the user is available",
                    ),
                ),
                (
                    "comment",
                    models.TextField(blank=True, help_text="Optional comment or special requests"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "cycle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wishes",
                        to="food.foodteamcycle",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="food_team_wishes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "unique_together": {("cycle", "user")},
            },
        ),
    ]
