# Generated by Django 5.2.9 on 2026-01-18 11:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("food", "0009_replace_date_range_with_cooking_dates"),
    ]

    operations = [
        migrations.CreateModel(
            name="DriveMenuCache",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "week_number",
                    models.PositiveIntegerField(help_text="ISO week number (1-53)"),
                ),
                ("year", models.PositiveIntegerField(help_text="Year for the week")),
                (
                    "cook_name",
                    models.CharField(
                        blank=True,
                        help_text="Name of the cook for this week",
                        max_length=100,
                    ),
                ),
                (
                    "monday_menu",
                    models.TextField(blank=True, help_text="Monday's menu description"),
                ),
                (
                    "tuesday_menu",
                    models.TextField(blank=True, help_text="Tuesday's menu description"),
                ),
                (
                    "wednesday_menu",
                    models.TextField(blank=True, help_text="Wednesday's menu description"),
                ),
                (
                    "thursday_menu",
                    models.TextField(blank=True, help_text="Thursday's menu description"),
                ),
                (
                    "raw_content",
                    models.TextField(
                        blank=True,
                        help_text="Raw content from the document (for debugging)",
                    ),
                ),
                (
                    "drive_file_id",
                    models.CharField(
                        blank=True,
                        help_text="Google Drive file ID for reference",
                        max_length=100,
                    ),
                ),
                (
                    "fetched_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="When this menu was last fetched from Drive",
                    ),
                ),
            ],
            options={
                "ordering": ["-year", "-week_number"],
                "unique_together": {("week_number", "year")},
            },
        ),
    ]
