# Generated by Django 5.2.9 on 2026-01-18 11:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("food", "0010_add_drive_menu_cache"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="drivemenucache",
            name="cook_name",
        ),
    ]
