# Generated by Django 5.2.9 on 2026-01-18 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("food", "0011_remove_cook_name_from_drive_menu_cache"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="dailymenu",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="dailymenu",
            name="template",
        ),
        migrations.RemoveField(
            model_name="dailymenu",
            name="weekly_menu",
        ),
        migrations.RemoveField(
            model_name="weeklymenu",
            name="created_by",
        ),
        migrations.DeleteModel(
            name="MenuTemplate",
        ),
        migrations.DeleteModel(
            name="DailyMenu",
        ),
        migrations.DeleteModel(
            name="WeeklyMenu",
        ),
    ]
