# Generated by Django 5.2.9 on 2026-01-25 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("food", "0012_alter_dailymenu_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="foodteamcycle",
            name="status",
            field=models.CharField(
                choices=[
                    ("collecting_wishes", "Indsamler ønsker"),
                    ("generating", "Genererer hold"),
                    ("finalized", "Afsluttet"),
                    ("archived", "Arkiveret"),
                ],
                default="collecting_wishes",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="foodticket",
            name="meal_type",
            field=models.CharField(
                choices=[("meat", "Kød"), ("vegetarian", "Vegetar")],
                default="meat",
                help_text="Only relevant for Wednesday",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="mealpreference",
            name="day_of_week",
            field=models.IntegerField(
                choices=[(0, "Mandag"), (1, "Tirsdag"), (2, "Onsdag"), (3, "Torsdag")]
            ),
        ),
        migrations.AlterField(
            model_name="mealpreference",
            name="dining_option",
            field=models.CharField(
                choices=[("eat_in", "Spis i fælleshuset"), ("take_away", "Tag med")],
                default="eat_in",
                help_text="Default dining preference (eat in or take away)",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="mealregistration",
            name="dining_option",
            field=models.CharField(
                choices=[("eat_in", "Spis i fælleshuset"), ("take_away", "Tag med")],
                default="eat_in",
                help_text="Eat in or take away",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="mealregistration",
            name="meal_type",
            field=models.CharField(
                choices=[("meat", "Kød"), ("vegetarian", "Vegetar")],
                default="meat",
                help_text="Only relevant for Wednesday",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="teamswaprequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Afventer"),
                    ("accepted", "Accepteret"),
                    ("declined", "Afvist"),
                    ("cancelled", "Annulleret"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
