# Generated by Django 5.2.9 on 2026-03-02 14:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("food", "0016_remove_old_meal_type_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="foodticket",
            name="adults_veg",
            field=models.PositiveIntegerField(
                default=1, validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
        migrations.AlterField(
            model_name="mealpreference",
            name="adults_veg",
            field=models.PositiveIntegerField(
                default=1, validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
        migrations.AlterField(
            model_name="mealregistration",
            name="adults_veg",
            field=models.PositiveIntegerField(
                default=1, validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
    ]
