# Generated by Django 5.2.9 on 2026-03-05 20:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("food", "0017_alter_foodticket_adults_veg_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="drivemenucache",
            name="drive_folder_id",
            field=models.CharField(
                blank=True,
                help_text="Google Drive week folder ID (used for linking to the specific week's folder)",
                max_length=100,
            ),
        ),
    ]
