# Generated by Django 5.2.9 on 2026-04-02 11:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("food", "0019_registration_per_house"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="foodticket",
            name="owner",
            field=models.ForeignKey(
                help_text="The user who created this ticket listing",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="food_tickets",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="mealregistration",
            name="is_active",
            field=models.BooleanField(
                default=True, help_text="False if house cancelled this registration"
            ),
        ),
        migrations.CreateModel(
            name="ClosedFoodDay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True)),
                (
                    "reason",
                    models.CharField(
                        blank=True,
                        help_text="Valgfri begrundelse (f.eks. 'Helligdag', 'Ferie')",
                        max_length=200,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_closed_food_days",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["date"],
            },
        ),
    ]
