# Generated by Django 5.2.9 on 2026-05-03 12:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("food", "0020_closedfoodday"),
        ("houses", "0005_house_slug"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="foodticket",
            index=models.Index(fields=["house", "date"], name="ticket_house_date_idx"),
        ),
        migrations.AddIndex(
            model_name="foodticket",
            index=models.Index(fields=["claimed_by", "date"], name="ticket_claimedby_date_idx"),
        ),
        migrations.AddIndex(
            model_name="mealregistration",
            index=models.Index(fields=["date", "is_active"], name="mealreg_date_active_idx"),
        ),
    ]
