# Generated by Django 5.2.9 on 2026-05-27 21:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("food", "0021_foodticket_ticket_house_date_idx_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="drivemenucache",
            name="recipe_file_id",
            field=models.CharField(
                blank=True,
                help_text="Drive file ID of the week's recipe spreadsheet (if found).",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="drivemenucache",
            name="recipe_sheets",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Parsed recipe spreadsheet sheets for the week. List of {code, day, index, name, url} dicts (code like 'Ma1'; day 0-3; name from the sheet's A1 cell; url deep-links to the sheet).",
            ),
        ),
        migrations.AddField(
            model_name="foodteamwish",
            name="is_unavailable",
            field=models.BooleanField(
                default=False,
                help_text="User opted out of this cycle entirely (distinct from the permanent is_exempt_from_food_teams). The generator skips them for this cycle.",
            ),
        ),
        migrations.CreateModel(
            name="SwapBroadcast",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "available_dates",
                    models.JSONField(
                        default=list,
                        help_text="ISO date strings the requester is willing to cook instead.",
                    ),
                ),
                (
                    "candidate_user_ids",
                    models.JSONField(
                        default=list,
                        help_text="User IDs notified as candidates at creation time (for reference).",
                    ),
                ),
                ("message", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Åben"),
                            ("accepted", "Accepteret"),
                            ("cancelled", "Annulleret"),
                        ],
                        default="open",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "accepted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="accepted_broadcasts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "accepted_membership",
                    models.ForeignKey(
                        blank=True,
                        help_text="The accepting user's membership that was swapped in.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="accepted_broadcasts",
                        to="food.foodteammember",
                    ),
                ),
                (
                    "requester",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="swap_broadcasts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "requester_membership",
                    models.ForeignKey(
                        help_text="The membership (date) the requester wants to get rid of.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="broadcasts",
                        to="food.foodteammember",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TeamFavour",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "origin_date",
                    models.DateField(help_text="The cooking date that was taken over."),
                ),
                ("settled", models.BooleanField(default=False)),
                ("settled_at", models.DateTimeField(blank=True, null=True)),
                ("note", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "creditor",
                    models.ForeignKey(
                        help_text="The user who took over the shift (is owed a favour).",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favours_owed_to_me",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "cycle",
                    models.ForeignKey(
                        blank=True,
                        help_text="The cycle in which the takeover happened.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="favours",
                        to="food.foodteamcycle",
                    ),
                ),
                (
                    "debtor",
                    models.ForeignKey(
                        help_text="The user whose shift was taken over (owes a favour).",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favours_i_owe",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
