# Generated by Django 5.2.9 on 2026-08-02 19:10

from decimal import Decimal

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("food", "0021_foodticket_ticket_house_date_idx_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MealPrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "effective_from",
                    models.DateField(
                        help_text="Priserne gælder fra og med denne dato", unique=True
                    ),
                ),
                (
                    "price_adult_meat",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Pris pr. kødportion (voksen) i kr.",
                        max_digits=6,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                    ),
                ),
                (
                    "price_adult_veg",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Pris pr. vegetarportion (voksen) i kr.",
                        max_digits=6,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                    ),
                ),
                (
                    "price_child",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Pris pr. børneportion (1-12 år) i kr.",
                        max_digits=6,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                    ),
                ),
                (
                    "note",
                    models.CharField(
                        blank=True,
                        help_text="Valgfri begrundelse (f.eks. 'Prisstigning på råvarer')",
                        max_length=200,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_meal_prices",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-effective_from"],
            },
        ),
    ]
