# Generated by Django 5.2.9 on 2026-05-28 05:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("food", "0022_drivemenucache_recipe_file_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="foodteam",
            name="leftovers_announced_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the leftovers announcement was last sent.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="foodteam",
            name="leftovers_image_url",
            field=models.CharField(
                blank=True,
                help_text="Absolute URL of the uploaded leftovers photo, if any.",
                max_length=500,
            ),
        ),
        migrations.AddField(
            model_name="foodteam",
            name="leftovers_message",
            field=models.TextField(
                blank=True,
                help_text="Free-text message that came with the 'Rester er klar' announcement.",
            ),
        ),
    ]
