# Generated by Django 5.2.9 on 2026-06-05 19:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("food", "0023_foodteam_leftovers_announced_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="drivemenucache",
            name="daily_front_pages",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Parsed per-day 'forside' sections from the week's menu document. List of {day, weekday, title, blocks} dicts (day 0-3; blocks is a list of {text, heading}). Extracted from the detailed weekday pages of the .docx (one page per weekday).",
            ),
        ),
        migrations.AlterField(
            model_name="drivemenucache",
            name="recipe_sheets",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Parsed recipe spreadsheet sheets for the week. List of {code, day, index, name, weekday, url, ingredients, steps} dicts (code like 'Ma1'; day 0-3; name from cell C1; ingredients is a list of {amount, unit, name, comment}; steps is the Fremgangsmåde).",
            ),
        ),
    ]
