# Generated by Django 5.2.9 on 2026-08-10 13:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("food", "0023_seed_meal_prices"),
        ("food", "0024_drivemenucache_daily_front_pages_and_more"),
    ]

    operations = []
