# Generated by Django 5.2.9 on 2026-08-10 19:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("food", "0025_merge_20260810_1522"),
    ]

    operations = [
        migrations.AddField(
            model_name="foodteam",
            name="takeaway_announced_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the 'Takeaway er klar' announcement was sent.",
                null=True,
            ),
        ),
    ]
