# Generated by Django 5.2.9 on 2026-08-22 18:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("food", "0026_foodteam_takeaway_announced_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="foodteamwish",
            name="comment",
        ),
    ]
