# Generated by Django 5.2.9 on 2026-09-09 20:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("food", "0027_remove_foodteamwish_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="foodteamcycle",
            name="wish_reminder_sent_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the pre-deadline wish reminder was sent for this period.",
                null=True,
            ),
        ),
    ]
