# Generated by Django 5.2.9 on 2026-10-02 20:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("food", "0028_foodteamcycle_wish_reminder_sent_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="foodteam",
            name="takeaway_ready_at",
            field=models.TimeField(
                blank=True,
                help_text="Pickup time given with an advance 'Takeaway er klar' announcement.",
                null=True,
            ),
        ),
    ]
