# Generated by Django 5.2.9 on 2026-10-03 04:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("food", "0029_foodteam_takeaway_ready_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="foodteamwish",
            name="lifted_pause",
            field=models.BooleanField(
                default=False,
                help_text="Submitting this wish's dates ended the user's standing madhold pause.",
            ),
        ),
        migrations.AddField(
            model_name="foodteamwish",
            name="lifted_pause_reason",
            field=models.TextField(
                blank=True,
                help_text="The pause reason this wish cleared, restored if it is corrected to 'kan ikke'.",
            ),
        ),
    ]
