# Generated by Django 5.2.9 on 2026-03-04 12:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("announcements", "0002_add_announcement_attachment"),
    ]

    operations = [
        migrations.AddField(
            model_name="announcementattachment",
            name="preview_html",
            field=models.TextField(blank=True, default=""),
        ),
    ]
