# Generated by Django 5.2.9 on 2026-03-25 07:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("announcements", "0003_announcementattachment_preview_html"),
    ]

    operations = [
        migrations.AddField(
            model_name="announcement",
            name="show_on_dashboard",
            field=models.BooleanField(
                default=True,
                help_text="Show this announcement on the main dashboard page",
            ),
        ),
    ]
