# Generated by Django 5.2.9 on 2026-06-30 20:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("announcements", "0007_legacy_url_nullable"),
    ]

    operations = [
        migrations.AddField(
            model_name="announcementattachment",
            name="preview",
            field=models.ImageField(
                blank=True,
                help_text="Full-size web-viewable JPEG for formats browsers can't render (e.g. HEIC).",
                null=True,
                upload_to="announcement_attachments/previews/",
            ),
        ),
    ]
