/// <reference lib="webworker" />
import { cleanupOutdatedCaches, precacheAndRoute } from "workbox-precaching"

declare let self: ServiceWorkerGlobalScope

// Clean up old caches
cleanupOutdatedCaches()

// Precache all assets generated by the build
precacheAndRoute(self.__WB_MANIFEST)

// Handle push notifications
self.addEventListener("push", (event: PushEvent) => {
  // Must call waitUntil synchronously, before any async operations
  const promiseChain = (async () => {
    if (!event.data) {
      console.log("Push event received but no data")
      // Still show a generic notification on iOS
      await self.registration.showNotification("KB Intra", {
        body: "Du har en ny notifikation",
      })
      return
    }

    try {
      const data = event.data.json()
      // Keep options minimal for iOS Safari compatibility
      const options: NotificationOptions = {
        body: data.body || "Du har en ny notifikation",
        data: data.data || {},
      }

      // Only add icon if not on iOS (can cause issues)
      const isIOS = /iPhone|iPad|iPod/.test(self.navigator?.userAgent || "")
      if (!isIOS && data.icon) {
        options.icon = data.icon
      }

      await self.registration.showNotification(
        data.title || "KB Intra",
        options,
      )
    } catch (error) {
      console.error("Error handling push event:", error)
      // Fallback: show generic notification
      await self.registration.showNotification("KB Intra", {
        body: "Du har en ny notifikation",
      })
    }
  })()

  event.waitUntil(promiseChain)
})

// Handle notification click
self.addEventListener("notificationclick", (event: NotificationEvent) => {
  event.notification.close()

  const url = event.notification.data?.url || "/"

  event.waitUntil(
    self.clients
      .matchAll({ type: "window", includeUncontrolled: true })
      .then((clientList) => {
        // Check if there's already a window/tab open with the app
        for (const client of clientList) {
          if ("focus" in client) {
            client.focus()
            // Navigate to the notification's URL
            if ("navigate" in client) {
              client.navigate(url)
            }
            return
          }
        }
        // If no existing window, open a new one
        if (self.clients.openWindow) {
          return self.clients.openWindow(url)
        }
      }),
  )
})

// Handle push subscription change (when browser refreshes the subscription)
self.addEventListener("pushsubscriptionchange", () => {
  console.log("Push subscription changed")
  // The subscription will be re-registered when the user opens the app
})

// Handle skip waiting message from the client (for forced updates)
self.addEventListener("message", (event) => {
  if (event.data && event.data.type === "SKIP_WAITING") {
    console.log("[SW] Received SKIP_WAITING, activating new service worker")
    self.skipWaiting()
  }
})
