/// <reference lib="webworker" />
import { cleanupOutdatedCaches, precacheAndRoute } from "workbox-precaching"

declare let self: ServiceWorkerGlobalScope

// Clean up old caches
cleanupOutdatedCaches()

// Precache all assets generated by the build
precacheAndRoute(self.__WB_MANIFEST)

// Handle push notifications
self.addEventListener("push", (event: PushEvent) => {
  // Must call waitUntil synchronously, before any async operations
  const promiseChain = (async () => {
    if (!event.data) {
      console.log("Push event received but no data")
      // Still show a generic notification on iOS
      await self.registration.showNotification("KB Intra", {
        body: "Du har en ny notifikation",
      })
      return
    }

    try {
      const data = event.data.json()
      // Keep options minimal for iOS Safari compatibility
      const options: NotificationOptions = {
        body: data.body || "Du har en ny notifikation",
        data: data.data || {},
      }

      // Only add icon if not on iOS (can cause issues)
      const isIOS = /iPhone|iPad|iPod/.test(self.navigator?.userAgent || "")
      if (!isIOS && data.icon) {
        options.icon = data.icon
      }

      await self.registration.showNotification(
        data.title || "KB Intra",
        options,
      )
    } catch (error) {
      console.error("Error handling push event:", error)
      // Fallback: show generic notification
      await self.registration.showNotification("KB Intra", {
        body: "Du har en ny notifikation",
      })
    }
  })()

  event.waitUntil(promiseChain)
})

// Handle notification click
self.addEventListener("notificationclick", (event: NotificationEvent) => {
  event.notification.close()

  const notifUrl = event.notification.data?.url || "/"
  // Build absolute URL - notifUrl may be relative (e.g. "/forum/thread/123")
  const absoluteUrl = notifUrl.startsWith("http")
    ? notifUrl
    : self.location.origin + notifUrl

  event.waitUntil(
    self.clients
      .matchAll({ type: "window", includeUncontrolled: true })
      .then((clientList) => {
        // Only consider clients within our app's origin, not unrelated browser tabs
        const appClients = clientList.filter((client) =>
          client.url.startsWith(self.location.origin),
        )

        if (appClients.length > 0) {
          const client = appClients[0]
          client.focus()
          if ("navigate" in client) {
            client.navigate(absoluteUrl)
          }
          return
        }

        // If no existing window, open a new one
        if (self.clients.openWindow) {
          return self.clients.openWindow(absoluteUrl)
        }
      }),
  )
})

// Handle push subscription change (when browser refreshes the subscription)
// The SW cannot send authenticated API requests, so we notify the client
// to re-sync via usePushSubscriptionSync (which has access to the JWT).
// If no client is open, the next app open will re-sync automatically.
self.addEventListener("pushsubscriptionchange", (event: ExtendableEvent) => {
  console.log("[SW] Push subscription changed, notifying clients to re-sync")
  event.waitUntil(
    self.clients
      .matchAll({ type: "window", includeUncontrolled: true })
      .then((clients) => {
        for (const client of clients) {
          client.postMessage({ type: "PUSH_SUBSCRIPTION_CHANGED" })
        }
      }),
  )
})

// Handle skip waiting message from the client (for forced updates)
self.addEventListener("message", (event) => {
  if (event.data && event.data.type === "SKIP_WAITING") {
    console.log("[SW] Received SKIP_WAITING, activating new service worker")
    self.skipWaiting()
  }
})
