# Generated by Django 5.2.9 on 2026-08-25 12:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("forum", "0050_subgroup_reporting_enabled"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "number",
                    models.PositiveIntegerField(
                        help_text="Sagsnummer inden for udvalget — vises som #n."
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("defect", "Defekt inventar"),
                            ("faulty", "Fejlbehæftet inventar"),
                            ("suggestion", "Forslag til nyt inventar"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "Ny"),
                            ("in_progress", "I gang"),
                            ("awaiting_meeting", "Afventer udvalgsmøde"),
                            ("awaiting_other", "Afventer andet"),
                            ("done", "Afsluttet"),
                            ("rejected", "Afvist"),
                        ],
                        db_index=True,
                        default="new",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(help_text="Hvad er der sket.")),
                (
                    "location",
                    models.CharField(
                        blank=True,
                        help_text="Hvor det er, fx 'køkkenet i Hus 39'. Valgfri.",
                        max_length=200,
                    ),
                ),
                (
                    "legacy_reporter_name",
                    models.CharField(
                        blank=True,
                        help_text="Navn fra det gamle system, når indrapportøren ikke kunne matches til en bruger.",
                        max_length=150,
                    ),
                ),
                (
                    "legacy_url",
                    models.CharField(
                        blank=True,
                        help_text="Sagens adresse i Driftsudvalgets tidligere system.",
                        max_length=300,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "closed_at",
                    models.DateTimeField(
                        blank=True, help_text="Sat da sagen blev afsluttet eller afvist.", null=True
                    ),
                ),
                (
                    "subgroup",
                    models.ForeignKey(
                        help_text="Udvalget sagen er indrapporteret til.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to="forum.subgroup",
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ReportEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("created", "Sag oprettet"),
                            ("status", "Statusændring"),
                            ("comment", "Kommentar"),
                        ],
                        max_length=20,
                    ),
                ),
                ("old_status", models.CharField(blank=True, max_length=20)),
                ("new_status", models.CharField(blank=True, max_length=20)),
                ("message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        help_text="Tom for systemgenererede hændelser.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="report_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="reports.report",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="ReportPhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("image", models.ImageField(upload_to="report_photos/")),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True,
                        help_text="400px-longest-edge JPEG thumbnail, generated in the background.",
                        null=True,
                        upload_to="report_photos/thumbs/",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="reports.report",
                    ),
                ),
            ],
            options={
                "ordering": ["uploaded_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="report",
            constraint=models.UniqueConstraint(
                fields=("subgroup", "number"), name="unique_report_number_per_subgroup"
            ),
        ),
    ]
