# Generated by Django 5.2.9 on 2026-08-25 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("forum", "0050_subgroup_reporting_enabled"),
        ("reports", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReportCounter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "last_number",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Højeste sagsnummer der har været brugt — også hvis sagen siden er slettet.",
                    ),
                ),
                (
                    "subgroup",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="report_counter",
                        to="forum.subgroup",
                    ),
                ),
            ],
        ),
    ]
