# Generated by Django 5.2.9 on 2026-09-13 11:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reports", "0004_open_reporting_for_four_udvalg"),
    ]

    operations = [
        migrations.AlterField(
            model_name="report",
            name="kind",
            field=models.CharField(
                choices=[
                    ("defect", "Defekt"),
                    ("faulty", "Virker dårligt"),
                    ("suggestion", "Forslag"),
                ],
                db_index=True,
                max_length=20,
            ),
        ),
    ]
