# Generated by Django 5.2.9 on 2025-12-13 09:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("forum", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="subgroup",
            options={"ordering": ["-is_committee", "name"]},
        ),
        migrations.AddField(
            model_name="subgroup",
            name="is_committee",
            field=models.BooleanField(
                default=False,
                help_text="If true, this subgroup is a committee (Udvalg) and appears at the top.",
            ),
        ),
    ]
