# Generated by Django 5.2.9 on 2025-12-13 11:01

from django.db import migrations, models
import django.db.models.deletion


def populate_subgroup_from_folder(apps, schema_editor):
    """Populate subgroup field from folder's subgroup for existing files."""
    File = apps.get_model("forum", "File")
    for file in File.objects.filter(subgroup__isnull=True, folder__isnull=False):
        file.subgroup = file.folder.subgroup
        file.save()


class Migration(migrations.Migration):

    dependencies = [
        ("forum", "0003_add_is_committee_to_subgroup"),
    ]

    operations = [
        # Step 1: Add subgroup field as nullable
        migrations.AddField(
            model_name="file",
            name="subgroup",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="files",
                to="forum.subgroup",
            ),
        ),
        # Step 2: Make folder field nullable
        migrations.AlterField(
            model_name="file",
            name="folder",
            field=models.ForeignKey(
                blank=True,
                help_text="If null, file is at root level of the subgroup.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="files",
                to="forum.folder",
            ),
        ),
        # Step 3: Populate subgroup from folder for existing files
        migrations.RunPython(populate_subgroup_from_folder, migrations.RunPython.noop),
        # Step 4: Make subgroup non-nullable
        migrations.AlterField(
            model_name="file",
            name="subgroup",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="files",
                to="forum.subgroup",
            ),
        ),
    ]
