# Generated by Django 5.2.9 on 2026-01-11 16:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("forum", "0006_add_post_attachment"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="subgroup",
            options={"ordering": ["-is_main", "-is_committee", "-last_activity_at"]},
        ),
        migrations.AddField(
            model_name="subgroup",
            name="is_main",
            field=models.BooleanField(
                default=False,
                help_text="If true, this subgroup appears at the very top (e.g., Fælles).",
            ),
        ),
        migrations.AlterField(
            model_name="subgroup",
            name="is_committee",
            field=models.BooleanField(
                default=False,
                help_text="If true, this subgroup is a committee (Udvalg).",
            ),
        ),
    ]
