# Generated by Django 5.2.9 on 2026-01-25 21:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("forum", "0008_add_reaction_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="file",
            name="preview_html",
            field=models.TextField(
                blank=True,
                help_text="HTML preview for DOCX files, generated on upload.",
            ),
        ),
        migrations.AddField(
            model_name="postattachment",
            name="preview_html",
            field=models.TextField(
                blank=True,
                help_text="HTML preview for DOCX files, generated on upload.",
            ),
        ),
    ]
