# Generated by Django 5.2.9 on 2026-02-05 07:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("forum", "0009_add_preview_html"),
    ]

    operations = [
        migrations.AddField(
            model_name="thread",
            name="is_closed",
            field=models.BooleanField(
                default=False,
                help_text="If true, no new posts can be added to this thread.",
            ),
        ),
    ]
