# Generated by Django 5.2.9 on 2026-02-16 20:41

from django.db import migrations


def subscribe_all_to_faelles(apps, schema_editor):
    """Subscribe all active users to the 'Fælles' subgroup."""
    Subgroup = apps.get_model("forum", "Subgroup")
    SubgroupSubscription = apps.get_model("forum", "SubgroupSubscription")
    User = apps.get_model("users", "User")

    try:
        faelles = Subgroup.objects.get(name="Fælles")
    except Subgroup.DoesNotExist:
        return

    existing_user_ids = set(
        SubgroupSubscription.objects.filter(subgroup=faelles).values_list("user_id", flat=True)
    )
    users_to_subscribe = User.objects.filter(is_active=True).exclude(id__in=existing_user_ids)

    SubgroupSubscription.objects.bulk_create(
        [SubgroupSubscription(user=user, subgroup=faelles) for user in users_to_subscribe]
    )


class Migration(migrations.Migration):
    dependencies = [
        ("forum", "0013_populate_threadreadstatus"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(subscribe_all_to_faelles, migrations.RunPython.noop),
    ]
