# Generated by Django 5.2.9 on 2026-02-17 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("forum", "0014_subscribe_all_to_faelles"),
    ]

    operations = [
        migrations.AlterField(
            model_name="file",
            name="folder",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="files",
                to="forum.folder",
            ),
        ),
        migrations.AlterField(
            model_name="file",
            name="subgroup",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="files",
                to="forum.subgroup",
            ),
        ),
        migrations.AlterField(
            model_name="folder",
            name="subgroup",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="folders",
                to="forum.subgroup",
            ),
        ),
    ]
