# Generated by Django 5.2.9 on 2026-02-19 19:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("forum", "0015_allow_null_subgroup_on_folder_and_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="thread",
            name="slug",
            field=models.SlugField(allow_unicode=True, blank=True, max_length=200),
        ),
    ]
