# Generated by Django 5.2.9 on 2026-02-19 20:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("forum", "0018_thread_slug_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="content",
            field=models.TextField(blank=True, default=""),
        ),
    ]
