# Generated by Django 5.2.9 on 2026-02-28 07:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("forum", "0021_folder_slug"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="folder",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="pollvote",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="reaction",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="subgroupsubscription",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="thread",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="threadmutestatus",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="threadreadstatus",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="folder",
            constraint=models.UniqueConstraint(
                fields=("subgroup", "parent", "name"),
                name="unique_folder_subgroup_parent_name",
            ),
        ),
        migrations.AddConstraint(
            model_name="folder",
            constraint=models.UniqueConstraint(
                fields=("subgroup", "slug"), name="unique_folder_subgroup_slug"
            ),
        ),
        migrations.AddConstraint(
            model_name="pollvote",
            constraint=models.UniqueConstraint(
                fields=("option", "user"), name="unique_poll_vote_per_user"
            ),
        ),
        migrations.AddConstraint(
            model_name="reaction",
            constraint=models.UniqueConstraint(
                fields=("post", "user", "reaction_type"),
                name="unique_reaction_per_user",
            ),
        ),
        migrations.AddConstraint(
            model_name="subgroupsubscription",
            constraint=models.UniqueConstraint(
                fields=("user", "subgroup"), name="unique_user_subgroup"
            ),
        ),
        migrations.AddConstraint(
            model_name="thread",
            constraint=models.UniqueConstraint(
                fields=("subgroup", "slug"), name="unique_thread_subgroup_slug"
            ),
        ),
        migrations.AddConstraint(
            model_name="threadmutestatus",
            constraint=models.UniqueConstraint(
                fields=("user", "thread"), name="unique_thread_mute_status"
            ),
        ),
        migrations.AddConstraint(
            model_name="threadreadstatus",
            constraint=models.UniqueConstraint(
                fields=("user", "thread"), name="unique_thread_read_status"
            ),
        ),
    ]
