# Generated by Django 5.2.9 on 2026-03-11 21:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("forum", "0022_unique_together_to_constraints"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="edited_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Set when someone other than the author edits this post.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="edited_posts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
