# Generated by Django 5.2.9 on 2026-03-18 20:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("forum", "0022_unique_together_to_constraints"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reaction",
            name="reaction_type",
            field=models.CharField(
                choices=[
                    ("like", "👍"),
                    ("heart", "❤️"),
                    ("laugh", "😂"),
                    ("surprised", "😮"),
                    ("sad", "😢"),
                    ("celebrate", "🎉"),
                    ("claim", "🙋"),
                ],
                max_length=20,
            ),
        ),
    ]
