# Generated by Django 5.2.9 on 2026-03-19 15:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("forum", "0023_add_edited_by_to_post"),
        ("forum", "0023_alter_reaction_reaction_type"),
    ]

    operations = []
