# Generated by Django 5.2.9 on 2026-03-19 21:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("forum", "0023_alter_reaction_reaction_type"),
        ("forum", "0023_subgroup_group_conversation_subgroupmembership"),
    ]

    operations = []
