# Generated by Django 5.2.9 on 2026-03-25 07:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("forum", "0024_post_edited_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="subgroup",
            name="icon",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Tabler icon name for display, e.g. 'users', 'home'. Empty = default per type.",
                max_length=30,
            ),
        ),
    ]
