# Generated by Django 5.2.9 on 2026-04-08 08:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("forum", "0027_alter_post_edited_by"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="file",
            name="members_only",
            field=models.BooleanField(
                default=False,
                help_text="If true, only members of the subgroup (and the uploader) can see this file.",
            ),
        ),
        migrations.AddField(
            model_name="subgroup",
            name="allows_members",
            field=models.BooleanField(
                default=False,
                help_text="If true, this subgroup has formal members and can host members-only threads/files.",
            ),
        ),
        migrations.AddField(
            model_name="thread",
            name="members_only",
            field=models.BooleanField(
                default=False,
                help_text="If true, only members of the subgroup (and the author) can see this thread.",
            ),
        ),
        migrations.CreateModel(
            name="SubgroupMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        blank=True,
                        default="Medlem",
                        help_text="Free-text role label, e.g., 'Medlem', 'Formand', 'Kasserer'.",
                        max_length=100,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "subgroup",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="forum.subgroup",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subgroup_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "subgroup"),
                        name="unique_user_subgroup_membership",
                    )
                ],
            },
        ),
    ]
