# Generated by Django 5.2.9 on 2026-04-09 08:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("forum", "0029_committees_allow_members"),
    ]

    operations = [
        migrations.AddField(
            model_name="subgroup",
            name="links_info",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Rich text content for the 'Links og info' tab.",
            ),
        ),
    ]
