# Generated by Django 5.2.9 on 2026-04-10 07:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("forum", "0030_subgroup_links_info"),
    ]

    operations = [
        migrations.AddField(
            model_name="subgroup",
            name="default_members_only",
            field=models.BooleanField(
                default=False,
                help_text="If true, the 'Privat tråd' checkbox is checked by default when creating threads/files.",
            ),
        ),
    ]
