# Generated by Django 5.2.9 on 2026-04-10 10:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("forum", "0031_subgroup_default_members_only"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subgroupmembership",
            name="role",
            field=models.CharField(
                blank=True,
                default="Medlem",
                help_text="Free-text role label, e.g., 'Medlem', 'Leder', 'Kasserer'.",
                max_length=100,
            ),
        ),
    ]
