# Generated by Django 5.2.9 on 2026-04-10 19:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("forum", "0032_alter_subgroupmembership_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reaction",
            name="reaction_type",
            field=models.CharField(max_length=50),
        ),
    ]
