# Generated by Django 5.2.9 on 2026-04-23 06:22

from django.db import migrations, models

DEFAULT_ROLES = ["Medlem", "Leder", "Viseleder", "Sekretær", "Økonomi"]


def seed_roles_and_rename_kasserer(apps, schema_editor):
    SubgroupRoleOption = apps.get_model("forum", "SubgroupRoleOption")
    SubgroupMembership = apps.get_model("forum", "SubgroupMembership")

    for order, name in enumerate(DEFAULT_ROLES):
        SubgroupRoleOption.objects.get_or_create(name=name, defaults={"order": order})

    SubgroupMembership.objects.filter(role="Kasserer").update(role="Økonomi")


def reverse_seed(apps, schema_editor):
    SubgroupRoleOption = apps.get_model("forum", "SubgroupRoleOption")
    SubgroupRoleOption.objects.filter(name__in=DEFAULT_ROLES).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("forum", "0034_migrate_reaction_slugs_to_emoji"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubgroupRoleOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "order",
                    models.IntegerField(
                        default=0,
                        help_text="Lower numbers appear first in the role picker.",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "name"],
            },
        ),
        migrations.RunPython(seed_roles_and_rename_kasserer, reverse_seed),
    ]
