# Generated by Django 5.2.9 on 2026-04-30 13:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("forum", "0035_subgroup_role_options"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="post",
            index=models.Index(
                fields=["thread", "-created_at"], name="forum_post_thread_recent_idx"
            ),
        ),
    ]
