# Generated by Django 5.2.9 on 2026-04-30 20:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("forum", "0036_post_thread_created_at_index"),
    ]

    operations = [
        migrations.AddField(
            model_name="poll",
            name="allow_others_to_add_options",
            field=models.BooleanField(default=False),
        ),
    ]
