# Generated by Django 5.2.9 on 2026-05-16 06:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("forum", "0038_fix_subgroup_slugs"),
    ]

    operations = [
        migrations.AddField(
            model_name="subgroup",
            name="links_info_members",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Members-only rich text content shown below 'Links og info'.",
            ),
        ),
    ]
