# Generated by Django 5.2.9 on 2026-05-20 07:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("forum", "0039_subgroup_links_info_members"),
    ]

    operations = [
        migrations.AddField(
            model_name="postattachment",
            name="thumbnail",
            field=models.ImageField(
                blank=True,
                help_text="400px-longest-edge JPEG thumbnail for gallery/inline display.",
                null=True,
                upload_to="post_attachments/thumbs/",
            ),
        ),
    ]
