# Generated by Django 5.2.9 on 2026-06-10 20:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("forum", "0043_legacy_url_nullable_remaining"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subgroupsubscription",
            name="notify_replies",
        ),
    ]
