# Generated by Django 5.2.9 on 2026-06-30 20:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("forum", "0044_remove_subgroupsubscription_notify_replies"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="subgroup",
            options={"ordering": ["-is_main", "-is_committee"]},
        ),
    ]
