# Generated by Django 5.2.9 on 2026-06-30 20:07

from django.db import migrations


def rename_to_begivenheder(apps, schema_editor):
    """Rename the events catch-all subgroup's display name to 'Begivenheder'.

    The slug stays 'arrangementer' (a stable code key). get_or_create in the
    events code only sets defaults for a *new* row, so the existing production
    row keeps its old 'Arrangementer' name unless renamed here.
    """
    Subgroup = apps.get_model("forum", "Subgroup")
    Subgroup.objects.filter(slug="arrangementer", name="Arrangementer").update(
        name="Begivenheder",
        description="Diskussioner om begivenheder",
    )


def rename_to_arrangementer(apps, schema_editor):
    Subgroup = apps.get_model("forum", "Subgroup")
    Subgroup.objects.filter(slug="arrangementer", name="Begivenheder").update(
        name="Arrangementer",
        description="Diskussioner om arrangementer",
    )


class Migration(migrations.Migration):
    dependencies = [
        ("forum", "0045_alter_subgroup_options"),
    ]

    operations = [
        migrations.RunPython(rename_to_begivenheder, rename_to_arrangementer),
    ]
