# Generated by Django 5.2.9 on 2026-06-30 20:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("forum", "0046_rename_arrangementer_to_begivenheder"),
    ]

    operations = [
        migrations.AddField(
            model_name="postattachment",
            name="preview",
            field=models.ImageField(
                blank=True,
                help_text="Full-size web-viewable JPEG for formats browsers can't render (e.g. HEIC).",
                null=True,
                upload_to="post_attachments/previews/",
            ),
        ),
    ]
