# Generated by Django 5.2.9 on 2026-07-31 23:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("forum", "0048_reindex_renamed_subgroup"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="subgroup",
            options={"ordering": ["-is_main", "-is_committee", "name"]},
        ),
    ]
