# Generated by Django 5.2.9 on 2026-08-25 12:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("forum", "0049_alter_subgroup_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="subgroup",
            name="reporting_enabled",
            field=models.BooleanField(
                default=False,
                help_text="If true, residents can file reports (indrapporteringer) to this group and its members handle them. Members are the caseworkers, so pair this with allows_members.",
            ),
        ),
    ]
