# Generated by Django 5.2.9 on 2026-06-25 12:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("forum", "0049_subgroup_parent"),
    ]

    operations = [
        migrations.AddField(
            model_name="subgroup",
            name="established_on",
            field=models.DateField(
                blank=True,
                help_text="Official creation date, distinct from the system created_at timestamp.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="subgroup",
            name="expires_on",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="subgroup",
            name="is_active",
            field=models.BooleanField(
                db_index=True,
                default=True,
                help_text="False = afsluttet/arkiveret. Hidden from the forum list by default.",
            ),
        ),
    ]
