# Generated by Django 5.2.9 on 2026-06-25 09:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("forum", "0049_alter_subgroup_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="subgroup",
            name="group_type",
            field=models.CharField(
                choices=[
                    ("generalforsamling", "Generalforsamling"),
                    ("faellesmoede", "Fællesmøde"),
                    ("bestyrelse", "Bestyrelse"),
                    ("udvalg", "Udvalg"),
                    ("arbejdsgruppe", "Arbejdsgruppe"),
                    ("almindelig", "Almindelig gruppe"),
                ],
                db_index=True,
                default="almindelig",
                max_length=20,
            ),
        ),
    ]
