# Generated by Django 5.2.9 on 2026-06-25 09:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("forum", "0051_backfill_group_type"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="subgroup",
            options={"ordering": ["-is_main", "name"]},
        ),
        migrations.RemoveField(
            model_name="subgroup",
            name="is_committee",
        ),
    ]
