# Generated by Django 5.2.9 on 2026-09-28 11:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("forum", "0052_repair_legacy_mentions"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="client_token",
            field=models.UUIDField(
                blank=True,
                help_text="One per reply form. A retry with the same token gets this post back.",
                null=True,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="thread",
            name="client_token",
            field=models.UUIDField(
                blank=True,
                help_text="One per compose form. A retry with the same token gets this thread back.",
                null=True,
                unique=True,
            ),
        ),
    ]
