# Generated by Django 5.2.9 on 2026-06-25 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("forum", "0053_create_organer_and_subscribe_all"),
    ]

    operations = [
        migrations.AddField(
            model_name="subgroup",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                help_text="Soft navigation/structure link only — not a permission or visibility cascade.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="children",
                to="forum.subgroup",
            ),
        ),
    ]
