# Generated by Django 5.2.9 on 2025-12-11 21:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("houses", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="house",
            name="profile_picture",
            field=models.ImageField(blank=True, null=True, upload_to="house_pictures/"),
        ),
    ]
