# Generated by Django 5.2.9 on 2026-05-13 11:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("houses", "0005_house_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="car",
            name="license_plate",
            field=models.CharField(blank=True, default="", max_length=15),
        ),
    ]
