# Generated by Django 5.2.9 on 2026-05-13 12:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("houses", "0007_normalize_license_plates"),
    ]

    operations = [
        migrations.AddField(
            model_name="child",
            name="profile_picture",
            field=models.ImageField(blank=True, null=True, upload_to="child_pictures/"),
        ),
    ]
