# Generated by Django 5.2.9 on 2026-05-20 08:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("houses", "0008_child_profile_picture"),
    ]

    operations = [
        migrations.AddField(
            model_name="child",
            name="profile_picture_thumbnail",
            field=models.ImageField(
                blank=True,
                help_text="400x400 JPEG square crop, generated server-side on upload.",
                null=True,
                upload_to="child_pictures/thumbs/",
            ),
        ),
        migrations.AddField(
            model_name="house",
            name="profile_picture_thumbnail",
            field=models.ImageField(
                blank=True,
                help_text="400x400 JPEG square crop, generated server-side on upload.",
                null=True,
                upload_to="house_pictures/thumbs/",
            ),
        ),
    ]
