# Generated by Django 5.2.9 on 2026-07-31 22:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("houses", "0009_child_profile_picture_thumbnail_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="car",
            name="color",
            field=models.CharField(blank=True, default="", max_length=30),
        ),
        migrations.AddField(
            model_name="car",
            name="dogs_allowed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="car",
            name="equipment_note",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="car",
            name="has_charge_fob",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="car",
            name="has_isofix",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="car",
            name="has_tow_hitch",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="car",
            name="in_pool",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="car",
            name="make",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AddField(
            model_name="car",
            name="model_name",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AddField(
            model_name="car",
            name="practical_note",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="car",
            name="rate_per_km",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Overrides the shared default rate when set.",
                max_digits=5,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="car",
            name="seats",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="car",
            name="year",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
