# Generated by Django 5.2.9 on 2026-09-01 19:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("houses", "0010_car_color_car_dogs_allowed_car_equipment_note_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="child",
            options={
                "ordering": [models.OrderBy(models.F("birthdate"), nulls_last=True), "name"],
                "verbose_name_plural": "children",
            },
        ),
    ]
